apiVersion: v1
kind: Service
metadata:
  name: naniura-service
  namespace: preprod
spec:
  type: NodePort
  selector:
    app: naniura-nginx
  ports:
    - port: 84
      targetPort: 84
      nodePort: 30084
