apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
  namespace: preprod
data:
  default.conf: |
    server {
        listen 84;
        server_name localhost;
        root /usr/share/nginx/html;
        index home.html;
        location / {
            try_files $uri $uri/ =404;
        }
    }
